# Generated by Django 3.0.1 on 2019-12-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='id',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='idEmpleado',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
