# Generated by Django 3.0.1 on 2019-12-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191223_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ruc_cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=60)),
                ('responsable', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompraProducto',
            fields=[
                ('idCompra', models.IntegerField(primary_key=True, serialize=False)),
                ('idCliente', models.IntegerField()),
                ('idProducto', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('valorTotal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('idContato', models.IntegerField(primary_key=True, serialize=False)),
                ('idCliente', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('fechaContrato', models.DateField()),
                ('imagenContrato', models.CharField(max_length=50)),
                ('contratoTacito', models.BooleanField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codDepartamento', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idEspecialidad', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('empleado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=14)),
                ('valorCompra', models.FloatField()),
                ('valorVenta', models.FloatField()),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('nroReporte', models.IntegerField(primary_key=True, serialize=False)),
                ('cliente', models.IntegerField()),
                ('empleado', models.IntegerField()),
                ('fecha', models.DateField()),
                ('ordenTrabajo', models.CharField(max_length=50)),
                ('horaInicio', models.DateField()),
                ('horaFinal', models.DateField()),
                ('solucionado', models.BooleanField()),
                ('contrato', models.BooleanField()),
                ('facturar', models.BooleanField()),
                ('solicitadoPor', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteDetalle',
            fields=[
                ('idDetalleR', models.IntegerField(primary_key=True, serialize=False)),
                ('nroReporte', models.IntegerField()),
                ('rubro', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('tiempoTotal', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('valorHora', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='empleado',
            name='idEmpleado',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
